title: Kathryn Brown 
logo: "/images/image.png?raw=true"
description: Leadership Facilitator and Full-stack Developer
  <br>
  <br>
  <br>
  HTML, CSS, JavaScript, SQL
  Python (inc Pandas/NumPy/MatPlotLib)
  <br>
  <a href="https://www.linkedin.com/in/hirekathrynbrown/">View My LinkedIn Profile</a> 
  <br><br>

template: minimal
google_analytics: UA-000000-0 # your Google Analytics ID here
