title: Kathryn Brown # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below
  Leadership Facilitator and Full-stack Developer
  <br>
  <br>
  <br>
  HTML, CSS, JavaScript, SQL
  Python (inc Pandas/NumPy/MatPlotLib)
  <br>
  <a href="https://www.linkedin.com/in/hirekathrynbrown/">View My LinkedIn Profile</a> 
  <br><br>

template: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
