title: Kathryn Brown 
logo: "/images/image.png?raw=true"
description: Full-Stack Developer and Product Manager
  <br>
  <br>
  <br>
  HTML5
  CSS (Sass, Tailwind)
  JavaScript (React, Node)
  SQL (SQLite, PostgreSQL)
  Python (Pandas/NumPy/MatPlotLib)
  <br>
  <a href="https://www.linkedin.com/in/hirekathrynbrown/">View My LinkedIn Profile</a> 
  <br><br>

template: minimal
google_analytics: UA-000000-0 # your Google Analytics ID here
