title: Kathryn Brown 
logo: "/images/image.png?raw=true"
description: Full-Stack Developer and Product Manager
  <br>
  <br>
  <br>
  HTML5 <br>
  CSS (Sass, Tailwind) <br>
  JavaScript (React, Node) <br>
  SQL (SQLite, PostgreSQL) <br>
  Python (Pandas/NumPy/MatPlotLib) <br>
  <br>
  <a href="https://www.linkedin.com/in/hirekathrynbrown/">View My LinkedIn Profile</a> 
  <br><br>

template: minimal
google_analytics: UA-000000-0 # your Google Analytics ID here
